[["M_1_PI", "The reciprocal of pi, 1/\\pi "],
 ["M_2_PI", "Twice the reciprocal of pi, 2/\\pi "],
 ["M_2_SQRTPI", "Two divided by the square root of pi, 2/\\sqrt\\pi "],
 ["M_E", "The base of exponentials, e "],
 ["M_EULER", "Euler's constant, \\gamma "],
 ["M_LN10", "The natural logarithm of ten, \\ln(10) "],
 ["M_LN2", "The natural logarithm of two, \\ln(2) "],
 ["M_LNPI", "The natural logarithm of pi, \\ln(\\pi) "],
 ["M_LOG10E", "The base-10 logarithm of e, $\\log_{10}(e)$ \\log_10 (e) "],
 ["M_LOG2E", "The base-2 logarithm of e, \\log_2 (e) "],
 ["M_PI", "The constant pi, \\pi "],
 ["M_PI_2", "Pi divided by two, \\pi/2 "],
 ["M_PI_4", "Pi divided by four, \\pi/4 "],
 ["M_SQRT1_2", "The square root of one-half, $\\sqrt{1/2}$ \\sqrt@{1/2@} "],
 ["M_SQRT2", "The square root of two, \\sqrt 2 "],
 ["M_SQRT3", "The square root of three, \\sqrt 3 "],
 ["M_SQRTPI", "The square root of pi, \\sqrt\\pi "]]
