[["GSL_EIGEN_SORT_VAL_ASC", 0, ""],
 ["GSL_EIGEN_SORT_VAL_DESC", 1, ""],
 ["GSL_EIGEN_SORT_ABS_ASC", 2, ""],
 ["GSL_EIGEN_SORT_ABS_DESC", 3, ""],
 ["GSL_SUCCESS", 0, ""],
 ["GSL_FAILURE", -1, ""],
 ["GSL_CONTINUE", -2, "iteration has not converged"],
 ["GSL_EDOM", 1, "input domain error, e.g sqrt(-1)"],
 ["GSL_ERANGE", 2, "output range error, e.g. exp(1e100)"],
 ["GSL_EFAULT", 3, "invalid pointer"],
 ["GSL_EINVAL", 4, "invalid argument supplied by user"],
 ["GSL_EFAILED", 5, "generic failure"],
 ["GSL_EFACTOR", 6, "factorization failed"],
 ["GSL_ESANITY", 7, "sanity check failed - shouldn't happen"],
 ["GSL_ENOMEM", 8, "malloc failed"],
 ["GSL_EBADFUNC", 9, "problem with user-supplied function"],
 ["GSL_ERUNAWAY", 10, "iterative process is out of control"],
 ["GSL_EMAXITER", 11, "exceeded max number of iterations"],
 ["GSL_EZERODIV", 12, "tried to divide by zero"],
 ["GSL_EBADTOL", 13, "user specified an invalid tolerance"],
 ["GSL_ETOL", 14, "failed to reach the specified tolerance"],
 ["GSL_EUNDRFLW", 15, "underflow"],
 ["GSL_EOVRFLW", 16, "overflow"],
 ["GSL_ELOSS", 17, "loss of accuracy"],
 ["GSL_EROUND", 18, "failed because of roundoff error"],
 ["GSL_EBADLEN", 19, "matrix, vector lengths are not conformant"],
 ["GSL_ENOTSQR", 20, "matrix not square"],
 ["GSL_ESING", 21, "apparent singularity detected"],
 ["GSL_EDIVERGE", 22, "integral or series is divergent"],
 ["GSL_EUNSUP", 23, "requested feature is not supported by the hardware"],
 ["GSL_EUNIMPL", 24, "requested feature not (yet) implemented"],
 ["GSL_ECACHE", 25, "cache limit exceeded"],
 ["GSL_ETABLE", 26, "table limit exceeded"],
 ["GSL_ENOPROG", 27, "iteration is not making progress towards solution"],
 ["GSL_ENOPROGJ", 28, "jacobian evaluations are not improving the solution"],
 ["GSL_ETOLF", 29, "cannot reach the specified tolerance in F"],
 ["GSL_ETOLX", 30, "cannot reach the specified tolerance in X"],
 ["GSL_ETOLG", 31, "cannot reach the specified tolerance in gradient"],
 ["GSL_EOF", 32, "end of file"],
 ["GSL_IEEE_TYPE_NAN", 1, ""],
 ["GSL_IEEE_TYPE_INF", 2, ""],
 ["GSL_IEEE_TYPE_NORMAL", 3, ""],
 ["GSL_IEEE_TYPE_DENORMAL", 4, ""],
 ["GSL_IEEE_TYPE_ZERO", 5, ""],
 ["GSL_IEEE_SINGLE_PRECISION", 1, ""],
 ["GSL_IEEE_DOUBLE_PRECISION", 2, ""],
 ["GSL_IEEE_EXTENDED_PRECISION", 3, ""],
 ["GSL_IEEE_ROUND_TO_NEAREST", 1, ""],
 ["GSL_IEEE_ROUND_DOWN", 2, ""],
 ["GSL_IEEE_ROUND_UP", 3, ""],
 ["GSL_IEEE_ROUND_TO_ZERO", 4, ""],
 ["GSL_IEEE_MASK_INVALID", 1, ""],
 ["GSL_IEEE_MASK_DENORMALIZED", 2, ""],
 ["GSL_IEEE_MASK_DIVISION_BY_ZERO", 4, ""],
 ["GSL_IEEE_MASK_OVERFLOW", 8, ""],
 ["GSL_IEEE_MASK_UNDERFLOW", 16, ""],
 ["GSL_IEEE_MASK_ALL", 31, ""],
 ["GSL_IEEE_TRAP_INEXACT", 32, ""],
 ["GSL_INTEG_GAUSS15", 1, "15 point Gauss-Kronrod rule"],
 ["GSL_INTEG_GAUSS21", 2, "21 point Gauss-Kronrod rule"],
 ["GSL_INTEG_GAUSS31", 3, "31 point Gauss-Kronrod rule"],
 ["GSL_INTEG_GAUSS41", 4, "41 point Gauss-Kronrod rule"],
 ["GSL_INTEG_GAUSS51", 5, "51 point Gauss-Kronrod rule"],
 ["GSL_INTEG_GAUSS61", 6, "61 point Gauss-Kronrod rule"],
 ["GSL_MESSAGE_MASK_A", 1, ""],
 ["GSL_MESSAGE_MASK_B", 2, ""],
 ["GSL_MESSAGE_MASK_C", 4, ""],
 ["GSL_MESSAGE_MASK_D", 8, ""],
 ["GSL_MESSAGE_MASK_E", 16, ""],
 ["GSL_MESSAGE_MASK_F", 32, ""],
 ["GSL_MESSAGE_MASK_G", 64, ""],
 ["GSL_MESSAGE_MASK_H", 128, ""],
 ["GSL_VEGAS_MODE_IMPORTANCE", 1, ""],
 ["GSL_VEGAS_MODE_IMPORTANCE_ONLY", 0, ""],
 ["GSL_VEGAS_MODE_STRATIFIED", -1, ""]]
